# Generated by Django 3.1.4 on 2021-01-22 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210119_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='emali',
            new_name='email',
        ),
    ]
